import { questions } from "../data/teacherDashboardData.js";

export const conversationsSeed = [
  {
    id: 1,
    student: questions[0].student,
    email: "mia.harper@email.com",
    course: "Eastern Philosophy",
    question: questions[0].question,
    avatar: questions[0].avatar,
    time: "2m ago",
    status: "unanswered",
    unread: 1,
    progress: 72,
    joinedAt: "May 12, 2024",
    activeAt: "Today, 10:20 AM",
    completedLessons: "18 / 25",
    watchTime: "18h 24m",
    quizScore: "82%",
    messages: [
      {
        id: "m1",
        author: "student",
        text: "How can I apply the concept of 'wu wei' to modern project management?",
        time: "10:24 AM",
      },
      {
        id: "m2",
        author: "teacher",
        text:
          "Great question, Mia! Wu wei is about effortless action and working in harmony with circumstances. In project management, it means focusing on clarity, aligning with the team's natural strengths, and removing obstacles rather than forcing outcomes.",
        time: "10:28 AM",
      },
      {
        id: "m3",
        author: "student",
        text: "That makes sense! Could you give a practical example of how to do that in a team?",
        time: "10:31 AM",
      },
    ],
  },
  {
    id: 2,
    student: questions[1].student,
    email: "olivia.chen@email.com",
    course: "Research Skills",
    question: questions[1].question,
    avatar: questions[1].avatar,
    time: "38m ago",
    status: "unanswered",
    unread: 1,
    progress: 64,
    joinedAt: "Apr 28, 2024",
    activeAt: "Today, 9:42 AM",
    completedLessons: "11 / 18",
    watchTime: "11h 08m",
    quizScore: "78%",
    messages: [
      {
        id: "o1",
        author: "student",
        text: "How should I present my research hypothesis more rigorously?",
        time: "9:42 AM",
      },
    ],
  },
  {
    id: 3,
    student: "Ethan Nguyen",
    email: "ethan.nguyen@email.com",
    course: "Data Science Basics",
    question: "Can you explain more about overfitting?",
    avatar: questions[0].avatar,
    time: "1h ago",
    status: "unanswered",
    unread: 1,
    progress: 58,
    joinedAt: "Mar 19, 2024",
    activeAt: "Today, 8:15 AM",
    completedLessons: "9 / 16",
    watchTime: "7h 48m",
    quizScore: "74%",
    messages: [
      {
        id: "e1",
        author: "student",
        text: "Can you explain more about overfitting and how to avoid it?",
        time: "8:15 AM",
      },
    ],
  },
  {
    id: 4,
    student: "Sophie Martin",
    email: "sophie.martin@email.com",
    course: "UX/UI Design",
    question: "What tool do you recommend for wireframes?",
    avatar: questions[1].avatar,
    time: "3h ago",
    status: "answered",
    progress: 86,
    joinedAt: "Feb 04, 2024",
    activeAt: "Yesterday, 6:10 PM",
    completedLessons: "22 / 25",
    watchTime: "21h 12m",
    quizScore: "91%",
    messages: [
      {
        id: "s1",
        author: "student",
        text: "What tool do you recommend for fast wireframes?",
        time: "6:10 PM",
      },
      {
        id: "s2",
        author: "teacher",
        text: "Start with Figma for collaborative wireframes, then move to higher fidelity only after the flow is clear.",
        time: "6:22 PM",
      },
    ],
  },
  {
    id: 5,
    student: "Daniel Kim",
    email: "daniel.kim@email.com",
    course: "JavaScript Advanced",
    question: "I'm stuck at asynchronous functions.",
    avatar: questions[0].avatar,
    time: "5h ago",
    status: "answered",
    progress: 69,
    joinedAt: "Jan 21, 2024",
    activeAt: "Yesterday, 3:35 PM",
    completedLessons: "14 / 20",
    watchTime: "16h 02m",
    quizScore: "80%",
    messages: [
      {
        id: "d1",
        author: "student",
        text: "I'm stuck at asynchronous functions. When should I use async and await?",
        time: "3:35 PM",
      },
      {
        id: "d2",
        author: "teacher",
        text: "Use async and await when you need asynchronous code to read like a sequence of steps.",
        time: "3:51 PM",
      },
    ],
  },
];

export const filterTabs = [
  { label: "All", value: "all" },
  { label: "Unanswered", value: "unanswered" },
  { label: "Answered", value: "answered" },
];
